### ISSUE TITLE
Error in fitExtractVarPartModel: response variance < 1e-05

### ISSUE THREAD

**Issue by sklasek** [GabrielHoffman/variancePartition#101]
Hello,
I'm attempting to run fitExtractVarPartModel on a matrix of 5996 features by 120 samples, using a formula with fixed and random effects. I'm getting an error 

```
Model failed for 182 responses.

    ASV1918                                          ASV2129 
"Error in FUN(...): response variance < 1e-05\n" "Error in FUN(...): response variance < 1e-05\n" 
```

... and so on for all 182 features that failed.

Happy to provide a reproducible example, but since I couldn't find any documentation of this type of error message for this function, I was just curious if there's a simple explanation or workaround. (Personally, I would be fine with rounding down such small response variance values to 0).

I also ran this successfully on another matrix and saw several features that had variance values of 0.000000e+00 corresponding to my random effect.

Running variancePartition_1.34.0 on R 4.4.1, under macOS Sonoma 14.6.

Thanks for any insight!
Scott

**Comment by GabrielHoffman** [comment]
The issue is that some response variables do not have any variation.  The values are constant across all samples, or at least very close to constant.  If the variance of a response is <1e-05, an error is thrown.

See example here:
```r
library(variancePartition)
data(varPartData)

# manually set the expression of the first gene to be zero for all samples
geneExpr[1,] = 0

form <- ~ Age + (1 | Individual) + (1 | Tissue)
varPart <- fitExtractVarPartModel(geneExpr, form, info)
# Warning message:
# In .fitExtractVarPartModel(exprObj, formula, data, REML = REML,  :
#   Model failed for 1 responses.
#   See errors with attr(., 'errors')

attr(varPart, 'errors')
#                                          gene1 
# "Error in FUN(...): response variance < 1e-05\n" 
```
You should apply a filter before running variation partitioning analysis

Best,
Gabriel

**Comment by sklasek** [comment]
Thanks for the quick response @GabrielHoffman!

It turned out that each of these responses were zero values in my count matrix, and I should have caught that and filtered them out beforehand.
