### ISSUE TITLE
question: Using VariancePartition with other type of data

### ISSUE THREAD

**Issue by JABioinf** [GabrielHoffman/variancePartition#106]
Dear Gabriel Hoffman,
Thank you for developing this really useful package!
I find the approach really elegant, so I wanted to use the partition approach on other type of data than RNA counts. 

Can the variance partition function be applied directly on any type of numerical data, or is there some assumption about the data dimensions or distribution to respect? or is this to completely avoid?
in other word running directly: `fitExtractVarPartModel(matrix , formula =  form, covariate.metadata)` with matrix of values of enrichment score, or eigengenes values, or log-transformed cell proportions for instance.

The results I've obtained make sense, but I don't want to use the obtained "variance explained" values in a manuscript, if it's not accurate, and notably if that's a blatant misuse of your tool. (In that case, is there any other tool you could refer to to achieve similar variance partitioning on non-RNA-seq data?)
Thank you for your help,
Best,

**Comment by GabrielHoffman** [comment]
`variancePartition` works on any type of continuous data fit with a regression model
