### ISSUE TITLE
Mixed-effect model with Interaction with Dream

### ISSUE THREAD

**Issue by jezreel-me** [GabrielHoffman/variancePartition#12]
Hi, 

Thank you in advance for being always so responsive. I love the integration of mixed-effect modeling similar based on limma. Definitely useful! The following topic is not covered in your tutorial.

I'm trying to use a mixed-effect model to calculate the interaction between 2 terms, as in this paper: https://www.nature.com/articles/s41467-018-07042-y

They describe to have used:
"a mixed-effects model with terms for Stat3 genotype (LR/Stat3Δ/Δ versus CC-LR) and sex (female versus male) as well as interaction between the two factors" (Caetano et al)

I simulated such modeling with dream. Usually, when I model interactions in limma and LmFit, I usually double check the design matrix to make sure the interaction is properly considered, but voom-like objects are instead the substitute inputs of a design matrix and dream and LmFit for mixed-effects. 

Using your provided data, I implemented the following:

data(varPartDEdata)

# Specify parallel processing parameters
# this is used implicitly by dream() to run in parallel
param = SnowParam(4, "SOCK", progressbar=TRUE)
register(param)

# The variable to be tested must be a fixed effect
form.1 <- ~ Disease*Sex + (1|Individual) 

# estimate weights using linear mixed model of dream
vobjDream = voomWithDreamWeights( geneExpr, form, metadata )

# Fit the dream model on each gene
# By default, uses the Satterthwaite approximation for the hypothesis test
fitmm = dream( vobjDream, form, metadata )

My questions are:
To properly modeling for the interaction with dream:
1. Should the form be:
form <- ~ **0 +** Disease*Sex + (1|Individual) #Model without the intercept
or
form <- ~ **1 +** Disease*Sex + (1|Individual) # Including or not the number 1 is the same but I put it here for demonstration only

2. Why does dream does not allow a maximal random effect structure for interactions in the form when applying voomwithDreamWeights:
form <- ~ Disease*Sex + (1 **+ Disease*Sex** |Individual) 
vobjDream = voomWithDreamWeights( geneExpr, form, metadata )
Error in if (inherits(possibleError, "error") && grep("the fixed-effects model matrix is column rank deficient",  : 
  missing value where TRUE/FALSE needed
Is this the same as when the model can't converge in lme4?

3. Dream does not require a second function like eBayes, correct? the p-values and coefficient per feature (rows) are in fitmm.1[["p.value"]] and fitmm.1[["coefficients"]]

Thanks, 

Jez

**Comment by GabrielHoffman** [comment]
1) Formula `~ Disease*Sex + (1|Individual)` models individual as a random effect, and models Disease, Sex and the interaction term.  You don't need to drop the intercept.  

2) Due to the way your study is set up, the model you specified cannot be fit by lme4.  A formula like `(1+Time|Individual)` allows the effect of each individual to vary across time.  In your case, Sex (and possibly Disease) is *constant within* individual, so it can't be fit.

3) dream with a random effect does not `eBayes()` after.  If you fit a fixed effect model, you need to run `eBayes()`.  I have experimented with a modified version of empirical Bayes for dream, but it had a number of issues.  The theory breaks down with random effects.

**Comment by jezreel-me** [comment]
Very helpful responses.

One more questioned. I turned the formula into a fixed model effects:
form <- ~ 1 + Disease*Sex

and I got the following warnings:
vobjDream = voomWithDreamWeights( geneExpr, form, metadata )
Fixed effect model, using limma directly...

fitmm.1 = dream( vobjDream, form, metadata )
Fixed effect model, using limma directly...
User can apply eBayes() afterwards...

Does that mean that voomWithDreamWeights is using voom, and dream is using LmFit instead?

Thanks again!

**Comment by GabrielHoffman** [comment]
Instead of making the user switch to `voom/lmFit` when they make a changes to the formula, `voomWithDreamWeights/dream` call the standard limma functions when no random effect is specified.  But you do have to call `eBayes()` afterward in that case

**Comment by jezreel-me** [comment]
Great. Thank you very much!

Jez
