### ISSUE TITLE
residuals.MArrayLM incompatible with dream output

### ISSUE THREAD

**Issue by raungar** [GabrielHoffman/variancePartition#13]
Hi-

Thanks for all your help in the past! I am trying to get the residuals of my dream analysis, and it is unable to work with residuals.MArrayLM. From diving into some of the code, it appears that the function fitted() does not work with the fitmm output. I was wondering if there is a workaround or a fix for that! I am showing an example based on the vignette below.

From your vignette:
```
library('variancePartition')
library('edgeR')
library('BiocParallel')
data(varPartDEdata)

# filter genes by number of counts
isexpr = rowSums(cpm(countMatrix)>0.1) >= 5

# Standard usage of limma/voom
geneExpr = DGEList( countMatrix[isexpr,] )
geneExpr = calcNormFactors( geneExpr )

# make this vignette faster by analyzing a subset of genes
geneExpr = geneExpr[1:1000,]
param = SnowParam(4, "SOCK", progressbar=TRUE)
register(param)

# The variable to be tested must be a fixed effect
form <- ~ Disease + (1|Individual) 

# estimate weights using linear mixed model of dream
vobjDream2 = voomWithDreamWeights( geneExpr, form, metadata )

# Fit the dream model on each gene
# By default, uses the Satterthwaite approximation for the hypothesis test
fitmm2 = dream( vobjDream2, form, metadata )

print(fitted(fitmm2))
my_resid<-residuals.MArrayLM(fitmm2,vobjDream2$E)
print(my_resid)
```
has the error:
```
Error in fitted.MArrayLM(fitmm2) : 
  Object contains contrasts rather than coefficients, so fitted values cannot be computed.
Calls: print -> fitted -> fitted.MArrayLM

```

Thanks so much,
Rachel

**Comment by GabrielHoffman** [comment]
Hi Rachel, 
I solved this probem, but it isn't in the Bioconductor release yet.  You can install the package from this GitHub repo.  Then run:
```r
fitmm2 = dream( vobjDream2, form, metadata, computeResiduals=TRUE )
res = residuals(fitmm2)
```

Note that this can only return the residuals on the fitted dataset.  computeResiduals is FALSE by default because this step can take a lot of memory, and that can be an issue with very large datasets.

Cheers,
 Gabriel

**Comment by raungar** [comment]
Hi Gabriel-

Thank you for your speedy response!

Great! Just confirming this output is what the result of residuals.MArrayLM(fitmm2,vobjDream2) would be, so no need to pass the new fitmm2 output to this residuals.MArrayLM() function?

Thanks so much,
Rachel

**Comment by GabrielHoffman** [comment]
Correct.  The `residuals()` function works just as you expect

**Comment by raungar** [comment]
Thank you!
