### ISSUE TITLE
Extracting coefficients from model?

### ISSUE THREAD

**Issue by bl24** [GabrielHoffman/variancePartition#20]
Hello again,

I was wondering how you can extract coefficient information once you've done the fit linear (mixed) modeling on your data?

Thanks!

**Comment by GabrielHoffman** [comment]
It depends on precisely what you mean by "coefficients".  Here are 3 options

1) `dream` will return all regression coefficients.  

2) `fitVarPartModel` returns the full model fit for each gene but uses a lot of memory:

```r
# this returns the full result for every model fit, so 
# you can use vp[[j]] to get the lmer output for gene j
# But can take a lot of memory for large datasets
vpFull <- fitVarPartModel(geneExpr, form, male.neg.cov)
```

3) If you want the variance component estimates, you can run a custom function to extract a summary of each model

```r
vp_custom <- fitVarPartModel(geneExpr, form, male.neg.cov, fxn=function(fit){
	lme4::VarCorr(fit)
})
```
