### ISSUE TITLE
Problems running the examples 

### ISSUE THREAD

**Issue by yzharold** [GabrielHoffman/variancePartition#21]
Hi Gabriel, 

I am trying to learn how to run your model by trying the example you have provided in your package (varPartDEdata), however, got stuck with the error message, and need some help from you. 

Here are the codes:

```r
library(variancePartition)

sessionInfo()

data(varPartDEdata)


# filter genes by number of counts
isexpr = rowSums(cpm(countMatrix)>0.1) >= 5

# Standard usage of limma/voom
geneExpr = DGEList( countMatrix[isexpr,] )
geneExpr = calcNormFactors( geneExpr )

# make this vignette faster by analyzing a subset of genes

## ----dupCor, eval=TRUE----------------------------------------------------------------------------
# apply duplicateCorrelation is two rounds
design = model.matrix( ~ Disease, metadata)
vobj_tmp = voom( geneExpr, design, plot=FALSE)
dupcor <- duplicateCorrelation(vobj_tmp,design,block=metadata$Individual)

# run voom considering the duplicateCorrelation results
# in order to compute more accurate precision weights
# Otherwise, use the results from the first voom run
vobj = voom( geneExpr, design, plot=FALSE, block=metadata$Individual, correlation=dupcor$consensus)

# Estimate linear mixed model with a single variance component
# Fit the model for each gene, 
dupcor <- duplicateCorrelation(vobj, design, block=metadata$Individual)

# But this step uses only the genome-wide average for the random effect
fitDupCor <- lmFit(vobj, design, block=metadata$Individual, correlation=dupcor$consensus)

# Fit Empirical Bayes for moderated t-statistics
fitDupCor <- eBayes( fitDupCor )

## ----lmm, eval=TRUE, message=FALSE, fig.height=2, results='hide'----------------------------------
# Specify parallel processing parameters
# this is used implicitly by dream() to run in parallel
param = SnowParam(4, "SOCK", progressbar=TRUE)
register(param)

# The variable to be tested must be a fixed effect
form <- ~ Disease + (1|Individual)

# estimate weights using linear mixed modell of dream
vobjDream = variancePartition::voomWithDreamWeights(geneExpr, form, metadata)


# Fit the dream model on each gene
# By default, uses the Satterthwaite approximation for the hypothesis test
fitmm = dream(vobjDream, form, metadata,control=control1)
```

The error message happened after the line

```r
vobjDream = variancePartition::voomWithDreamWeights(geneExpr, form, metadata)

Error in .fitVarPartModel(exprObj, formula, data, REML = REML, useWeights = useWeights,  : 
  the fixed-effects model matrix is column rank deficient (rank(X) = 1 < 2 = p);
the fixed effects will be jointly unidentifiable 

Suggestion: rescale fixed effect variables.
This will not change the variance fractions or p-values.
In addition: Warning message:
In qr2rankMatrix(q.r, tol = tol, isBqr = x.dense, do.warn = warn.qr) :
  qr2rankMatrix(.): QR has negative diag(R) entries
```

My sessionInfo is here:
```r
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] lme4_1.1-23               Matrix_1.3-0              BiocParallel_1.20.1       edgeR_3.28.1             
 [5] variancePartition_1.19.13 Biobase_2.46.0            BiocGenerics_0.32.0       scales_1.1.1             
 [9] foreach_1.5.0             limma_3.42.2              ggplot2_3.3.2            

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6       plyr_1.8.6         nloptr_1.2.2.1     pillar_1.4.4       compiler_3.6.3     tools_3.6.3       
 [7] prettyunits_1.1.1  progress_1.2.2     bitops_1.0-6       iterators_1.0.12   boot_1.3-25        statmod_1.4.34    
[13] lifecycle_0.2.0    tibble_3.0.1       gtable_0.3.0       nlme_3.1-144       lattice_0.20-38    pkgconfig_2.0.3   
[19] rlang_0.4.6        stringr_1.4.0      withr_2.2.0        dplyr_1.0.0        hms_0.5.3          generics_0.0.2    
[25] vctrs_0.3.1        gtools_3.8.2       caTools_1.18.0     locfit_1.5-9.4     grid_3.6.3         tidyselect_1.1.0  
[31] glue_1.4.1         R6_2.4.1           snow_0.4-3         minqa_1.2.4        gdata_2.18.0       reshape2_1.4.4    
[37] purrr_0.3.4        magrittr_1.5       colorRamps_2.3     gplots_3.0.3       codetools_0.2-16   ellipsis_0.3.1    
[43] splines_3.6.3      MASS_7.3-51.6      pbkrtest_0.4-8.6   colorspace_1.4-2   KernSmooth_2.23-17 stringi_1.4.6     
[49] doParallel_1.0.15  munsell_0.5.0      crayon_1.3.4      
```
Thanks a lot for your time and effort for this question. 

Harold

**Comment by GabrielHoffman** [comment]
Hi Harold, 
I ran this code on OS X with R 4.0.1 and Ubuntu with R 3.6.0 and I didn't get the error.  Can you provide a 'minimal reproducible example' that starts with a new R session.  I think the cause of the error is not in your current code, so I can't reproduce it

Gabriel

**Comment by yzharold** [comment]
Thanks a lot for your update, I ran the above code in the windows machine instead of OS X or Linux, does that make a difference? BTW, I did not use any other data set rather than the data you offered in the variantPartition package. My code provided above is the full code that I have run, but not be able to finish. 

Thanks, 

Harold

**Comment by GabrielHoffman** [comment]
Are you sure this this is the full code because even running the first 3 lines should produce an error:
```r
library(variancePartition)
data(varPartDEdata)
isexpr = rowSums(cpm(countMatrix)>0.1) >= 5
#> Error in h(simpleError(msg, call)): error in evaluating the argument 'x' in selecting a method for function 'rowSums': could not find function "cpm"
```
since the function `cpm` is not directly imported.  

The problem with your `variancePartition` example is that your R session is reloading packages and data from a previous session that is not included in your code.  You can create a clean R session with `ctrl+shift+F10` followed by `rm(list=ls())` start with no packages or data loaded.  The code is only reproducible if you start from a clear session.

**Comment by yzharold** [comment]
Thanks a lot for your input, here I have created a better example 

#############################


rm(list=ls())

library(variancePartition)

library(edgeR)
library(BiocParallel)
library(lme4)


sessionInfo()

data(varPartDEdata)


# filter genes by number of counts
isexpr = rowSums(cpm(countMatrix)>0.1) >= 5

# Standard usage of limma/voom
geneExpr = DGEList( countMatrix[isexpr,] )
geneExpr = calcNormFactors( geneExpr )

# make this vignette faster by analyzing a subset of genes



## ----dupCor, eval=TRUE----------------------------------------------------------------------------
# apply duplicateCorrelation is two rounds
design = model.matrix( ~ Disease, metadata)
vobj_tmp = voom( geneExpr, design, plot=FALSE)
dupcor <- duplicateCorrelation(vobj_tmp,design,block=metadata$Individual)

# run voom considering the duplicateCorrelation results
# in order to compute more accurate precision weights
# Otherwise, use the results from the first voom run
vobj = voom( geneExpr, design, plot=FALSE, block=metadata$Individual, correlation=dupcor$consensus)

# Estimate linear mixed model with a single variance component
# Fit the model for each gene, 
dupcor <- duplicateCorrelation(vobj, design, block=metadata$Individual)

# But this step uses only the genome-wide average for the random effect
fitDupCor <- lmFit(vobj, design, block=metadata$Individual, correlation=dupcor$consensus)

# Fit Empirical Bayes for moderated t-statistics
fitDupCor <- eBayes( fitDupCor )

## ----lmm, eval=TRUE, message=FALSE, fig.height=2, results='hide'----------------------------------
# Specify parallel processing parameters
# this is used implicitly by dream() to run in parallel
param = SnowParam(4, "SOCK", progressbar=TRUE)
register(param)

# The variable to be tested must be a fixed effect
form <- ~ Disease + (1|Individual)

# estimate weights using linear mixed modell of dream
vobjDream = variancePartition::voomWithDreamWeights(geneExpr, form, metadata)


# Fit the dream model on each gene
# By default, uses the Satterthwaite approximation for the hypothesis test
fitmm = dream(vobjDream, form, metadata,control=control1)


The error message happened in the same position
> # estimate weights using linear mixed modell of dream
> vobjDream = variancePartition::voomWithDreamWeights(geneExpr, form, metadata)
Error in .fitVarPartModel(exprObj, formula, data, REML = REML, useWeights = useWeights,  : 
  the fixed-effects model matrix is column rank deficient (rank(X) = 1 < 2 = p);
the fixed effects will be jointly unidentifiable 

Suggestion: rescale fixed effect variables.
This will not change the variance fractions or p-values.
In addition: Warning message:
In qr2rankMatrix(q.r, tol = tol, isBqr = x.dense, do.warn = warn.qr) :
  qr2rankMatrix(.): QR has negative diag(R) entries


My sessionInfo

> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] lme4_1.1-23               Matrix_1.3-0             
 [3] BiocParallel_1.20.1       edgeR_3.28.1             
 [5] variancePartition_1.19.13 Biobase_2.46.0           
 [7] BiocGenerics_0.32.0       scales_1.1.1             
 [9] foreach_1.5.0             limma_3.42.2             
[11] ggplot2_3.3.2            

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6       plyr_1.8.6         nloptr_1.2.2.1     pillar_1.4.4      
 [5] compiler_3.6.3     tools_3.6.3        prettyunits_1.1.1  progress_1.2.2    
 [9] bitops_1.0-6       iterators_1.0.12   boot_1.3-25        statmod_1.4.34    
[13] lifecycle_0.2.0    tibble_3.0.1       gtable_0.3.0       nlme_3.1-144      
[17] lattice_0.20-38    pkgconfig_2.0.3    rlang_0.4.6        stringr_1.4.0     
[21] withr_2.2.0        dplyr_1.0.0        hms_0.5.3          generics_0.0.2    
[25] vctrs_0.3.1        gtools_3.8.2       caTools_1.18.0     locfit_1.5-9.4    
[29] grid_3.6.3         tidyselect_1.1.0   glue_1.4.1         R6_2.4.1          
[33] minqa_1.2.4        gdata_2.18.0       reshape2_1.4.4     purrr_0.3.4       
[37] magrittr_1.5       colorRamps_2.3     gplots_3.0.3       codetools_0.2-16  
[41] ellipsis_0.3.1     splines_3.6.3      MASS_7.3-51.6      pbkrtest_0.4-8.6  
[45] colorspace_1.4-2   KernSmooth_2.23-17 stringi_1.4.6      doParallel_1.0.15 
[49] munsell_0.5.0      crayon_1.3.4

**Comment by GabrielHoffman** [comment]
I am not able to reproduce the error on OS X, Ubuntu or Windows 10.  Can you reproduce it on another machine? 

Your error suggests that the formula you are using produces a degenerate model that is "column rank deficient".

**Comment by yzharold** [comment]
I have tried the package on a different windows 10 machine, and it worked, just wonder whether you have any idea what could be the issue? BTW, the first machine is my working machine, the second machine is my personal computer. 

Thanks, 

Harold

**Comment by GabrielHoffman** [comment]
It looks like some data or package is being restored from a previous session.  Instead of using the dataset you expect, VariancePartition is finding an issue with this other loaded data and throwing an error.  You should  be able to disable session reloading

**Comment by yzharold** [comment]
Thanks a lot Gabriel, I will take a closer look about your suggestion. 

Harold

**Comment by ansonkn** [comment]
I don't know if there is a different solution to this but I have recently encountered the same problem where all of my previous analysis with Dream were no longer reproducible. It threw the error "Error in .fitVarPartModel(exprObj, formula, data, REML = REML, useWeights = useWeights,  : the fixed-effects model matrix is column rank deficient ". 
After a few weeks of frustration, I realize the problem had to do with the version of R being different from the one in which variancePartition was initially installed. The remedy was to remove variancePartition, install the latest version of R and then install variancePartition again through github. I hope this helps whoever might be having the same problem.

**Comment by mcieslik-mctp** [comment]
I ran into this issue, and can confirm Gabriels, dev-branch solution works.

**Comment by GabrielHoffman** [comment]
I will post here once the default CRAN `Matrix` is updated to solve this issue.  Thanks for your patience.

Gabriel

**Comment by GabrielHoffman** [comment]
The new CRAN release, `Matrix v1.3-2`, solves this issue
