### ISSUE TITLE
Error in case of missing samples

### ISSUE THREAD

**Issue by pbalajiv** [GabrielHoffman/variancePartition#23]
I am getting the following error. 
```
Error in if (inherits(possibleError, "error") && grep("the fixed-effects model matrix is column rank deficient",  : 
  missing value where TRUE/FALSE needed
```
I believe this is due to missing samples. I have 3 samples missing in my data. However, there are no NA values in my data. Do you think this could be fixed?

**Comment by GabrielHoffman** [comment]
Can you post a minimal reproducible example?

**Comment by pbalajiv** [comment]
Hi Gabriel
I had few other questions. I'm trying to model an RNAseq data where we have 87 samples (3 missing). These were measured from 15 subjects, over 6 time points (days 0, 1, 3, 7, 14, 28 and 56). As covariates, I have cumulative bacterial load (CFU) in each subject and batch information. I would like to model this data. I am basically interested in the differential expression for each time point compared against day 0 while accounting for subject ID, CFU and batch information. I believe that the time point should be modelled as a categorical variable, if I'm not much mistaken. As of now, I take time as a numerical variable, since the package does not allow categorical variables to become fixed effects. 
This is the design and model I'm using currently is
design <- model.matrix( ~ Timepoint, coldata)
form <- ~ (1|Subject_ID) + (1|Batch_info) + Timepoint + CFU
I am using CFU as a fixed effect (numerical) since only 3 subjects have CFU = 0 (forming a group). The rest have differing values of CFU.
Is this problem a good case for mixed effect linear modelling? 
Does differential expression analysis make sense with this formula? 
Regards

**Comment by GabrielHoffman** [comment]
There are two distinct types of analysis implemented in the package: 1) variance partitioning with `fitExtractVarPartModel` and 2) differential expression with `dream`.  While both methods are based on a linear mixed model and share a lot of code in the backend, the goals the requirements of the analyses are slightly different.  In variance partitioning categorical variables must be random for accurate estimate of the variance fractions.  But in differential expression with `dream` they can be fixed.

Your analysis setup looks good, but in the differential expression analysis you should make sure that TimePoint is categorical and uses time zero as a baseline.

**Comment by pbalajiv** [comment]
Thanks a lot, Gabriel. That clears a lot of my doubts.

**Comment by pbalajiv** [comment]
I am trying to use eBayesFMT function. I need this for downstream analysis using the package t-mod. Is 'eBayesFMT' functional as of now? 

Here is my session info:
```
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] BiocParallel_1.18.1       edgeR_3.26.8              tmod_0.44                
 [4] forcats_0.4.0             stringr_1.4.0             dplyr_0.8.3              
 [7] purrr_0.3.2               readr_1.3.1               tidyr_1.0.0              
[10] tibble_2.1.3              tidyverse_1.2.1           variancePartition_1.19.15
[13] Biobase_2.44.0            BiocGenerics_0.30.0       scales_1.0.0             
[16] foreach_1.4.7             limma_3.40.6              ggplot2_3.2.1  
```

**Comment by GabrielHoffman** [comment]
I strongly recommend against using `eBayesFMT`.  I included it in the package so that my simulations from the paper are reproducible.  But in practice `eBayesFMT` does not perform well.
