### ISSUE TITLE
Broken error check in .fitVarPartModel produces uninterpretable error message

### ISSUE THREAD

**Issue by DarwinAwardWinner** [GabrielHoffman/variancePartition#26]
I was trying to fit a model to just the first 100 samples in my data as a test, but this apparently produced an error. However, code in `.fitVarPartModel` that checks the error message in order to produce a more relevant diagnostic message encountered an error of its own:

```
>         a <- voomWithDreamWeights(
+             counts = dge[1:10,1:100],
+             formula = model_formulas[[model_name]],
+             data = dge$samples[1:100,]
+         )
Error in if (inherits(possibleError, "error") && grep("the fixed-effects model matrix is column rank deficient",  :
  missing value where TRUE/FALSE needed
In addition: Warning message:
In .fitVarPartModel(exprObj, formula, data, REML = REML, useWeights = useWeights,  :
  Sample names of responses (i.e. columns of exprObj) do not match
sample names of metadata (i.e. rows of data).  Recommend consistent
names so downstream results are labeled consistently.
> traceback(max.lines = 3)
8: .fitVarPartModel(exprObj, formula, data, REML = REML, useWeights = useWeights,
       weightsMatrix = weightsMatrix, showWarnings = showWarnings,
       fxn = fxn, control = control, quiet = quiet, BPPARAM = BPPARAM,
    ...
7: fitVarPartModel(y, formula, data, showWarnings = FALSE, ...,
       fxn = function(fit) {
           list(sd = attr(VarCorr(fit), "sc"), fitted.values = predict(fit))
    ...
6: fitVarPartModel(y, formula, data, showWarnings = FALSE, ...,
       fxn = function(fit) {
           list(sd = attr(VarCorr(fit), "sc"), fitted.values = predict(fit))
    ...
5: (function (counts, formula, data, lib.size = NULL, normalize.method = "none",
       span = 0.5, plot = FALSE, save.plot = FALSE, quiet = FALSE,
       BPPARAM = bpparam(), ...)
    ...
4: eval(mc, parent.frame())
3: eval(mc, parent.frame())
2: withVisible(eval(mc, parent.frame()))
1: voomWithDreamWeights(counts = dge[1:10, 1:100], formula = model_formulas[[model_name]],
       data = dge$samples[1:100, ])
```

I would recommend either rewriting the condition so that it can never return NA or else using one of `isTRUE` or `isFALSE` as appropriate.

**Comment by GabrielHoffman** [comment]
Can you provide the package version and a minimal reproducible example?

**Comment by DarwinAwardWinner** [comment]
Hmm, so it looks like only the code from my recent pull request was producing the offending error, so I can't easily provide a reproducible example. It's also not obvious to me, on further inspection, how the conditional could possibly have returned NA, since `grep` is only supposed to return NA if pattern is NA. Still, I think it's safer to add `isTRUE` to these conditionals. In my case, the actual error turned out to be `Error: number of levels of each grouping factor must be < number of observations (problems: Corrected_Blood_Sample)`. I was only able to get that error message after adding `isTRUE` to the appropriate conditionals.
