### ISSUE TITLE
Analysis repeated measurement data with dream

### ISSUE THREAD

**Issue by YouthYong** [GabrielHoffman/variancePartition#35]
Hi Dr. Hoffman,
I would like to use dream for 3 timepoint RNA-sequencing data. I would like to figure out the genes that were not affected by timepoint.  
My code so far looks like this:
form <- ~ time + (1|sex) + (1|age)
vobjDream = voomWithDreamWeights( geneExpr, form, info ,normalize.method="none")
fitmm = dream( vobjDream, form, info ,BPPARAM=param)
My metadata（named “info”） looks like this:
![image](https://user-images.githubusercontent.com/86392527/123197593-4c212180-d4de-11eb-9c91-f5990fd83beb.png)
I am not sure if this is the best way to do it. Do you have any advice?

Thank you very much for your advice
YouthYong

**Comment by GabrielHoffman** [comment]
In your case, it doesn't look like you have 'repeated measures' defined as multiple observations from the same biological sample or individual.  It looks like you have a distinct set of individuals observed at each time point.  You could certainly use `dream` but you could also use `limma/voom` too.  

Looking at your formula, you need to consider that only categorical variables can be modeled at random effects.  `sex` is categorical so `(1|sex)` is fine, but age is a continuous variable.  Running analyses with `(1|age)` is problematic and should produce an error or warning.

Gabriel

**Comment by YouthYong** [comment]
Hi Dr. Hoffman,
Thank you for you response. I didn't show my whole metadata ,my data contains observations from the same biological sample or individual at each time point. In term of the result of dream，if p value >0.05, does it mean that this gene was not affected by timepoint?
Thank you for your time.
YouthYong
