### ISSUE TITLE
Dream function: Please throw informative error message

### ISSUE THREAD

**Issue by arnaudmgh** [GabrielHoffman/variancePartition#36]
**Function call**:
`dream(vobjDream, form, metadata)`

**Error message**: 
`Error in { : task 1 failed - "$ operator is invalid for atomic vectors"`

**Workaround**:
I removed rows with any `NA` in metadata and it worked.

**Request**:
I don't know if the function is supposed to handle missing values. If it is, then I suppose this is a bug? 

In any case, it could help to add a check for `any(is.na(metadata))`, and at least throw an *informative* warning, saying that some variables in the model have NAs, at that it could case the dream function to fail.

**Comment by GabrielHoffman** [comment]
Thanks for the bug report.  Do you have a minimal reproducible example, and can you show `sessionInfo()`

Best,
Gabriel

**Comment by GabrielHoffman** [comment]
Try v1.21.8 for improved error messages and bug fixes

Gabriel
