### ISSUE TITLE
Reference manual and dream vignette say dream function replaces lmFit and returns fit without eBayes but you never call eBayes after

### ISSUE THREAD

**Issue by hermidalc** [GabrielHoffman/variancePartition#4]
The reference manual says the `dream` function fits a linear mixed model, like `lmFit`, and returns a linear model fit object just like `lmFit` before any `eBayes` or `treat`:

`MArrayLM2 object (just like MArrayLM from limma), and the directly estimated p-value (without eBayes)`

Your dream vignette also says the `dream` function replaces `lmFit`, though in your examples in the vignette and the reference manual I do not see any subsequent call to `eBayes` using the fit returned by `dream`.

Can I call `eBayes` or `treat` after or is `dream` automatically doing it?  If it is doing it, I think most users would prefer it not do that so that they have the option to call `treat` for proper lfc thresholding, which is something I would like to do.

**Comment by hermidalc** [comment]
I'm thinking that maybe that you purposely omit calling `eBayes` on a `dream` fit because DFs are per-gene and the t-statistics are not comparable, and therefore it wouldn't work with `eBayes` (or `treat`)?

If so, it would be nice to have some functionality like `treat` incorporated into `dream` where users can specify a biologically meaningful `lfc` absolute log-fold change threshold that the `dream` function will use to compute the appropriate statistics and p-values relevant to such a threshold and give more weight to fold-changes in gene ranking.  I would look at `treat` in limma for more details.

**Comment by GabrielHoffman** [comment]
I developed this over the course of a few months, and it seems like the documentation diverged from the implementation on this one.  I just posted a new version to GitHub:

```
CHANGES IN VERSION 1.15.8
-------------------------
o Replace cat() with message()
o add quiet option to a few functions
o dream() does not call eBayes() when lmFit() is used
```

The new vignette reads: "Note that if a random effect is not specified, dream() automatically uses lmFit(), but the user must run eBayes() afterward."

Unfortunately, `dream()`with random effects is not compatible with `eBayes()` or `treat()`.  But `topTable()` does have an `lfc` argument to apply a cutoff on the log fold change.

**Comment by hermidalc** [comment]
> Unfortunately, `dream()`with random effects is not compatible with `eBayes()` or `treat()`. But `topTable()` does have an `lfc` argument to apply a cutoff on the log fold change.

That makes sense and yep I suspected that it wouldn't be suitable.  Thanks very much for the explanation and the updates!
