### ISSUE TITLE
underlying assumptions input data

### ISSUE THREAD

**Issue by guidohooiveld** [GabrielHoffman/variancePartition#43]
Hi,
First of all, thanks very much for developing such useful package!

I have a question on the input data, specifically regarding the underlying requirements / assumptions made for the input data.
Reason for asking: for some explorative analysis I try to combine data from a range of experiments (obtained from GEO) that were run on different Affymetrix array platforms. To do so I am applying the so-called `YuGene` transformation. In essence this means that for each sample the expression data is rescaled, and is constrained (ranges) between 0 and 1. See [Yugene paper ](https://doi.org/10.1016/j.ygeno.2014.03.001)for more details.

Question: does this type of signal (re)distribution invalidate the underlying assumptions of the data characteristics that `variancePartition` expects? In other words, `YuGene` transformed data **is**, or rather **is not**, suited for analysis with `variancePartition`?

Thanks for any insights on this!
G

FWIW1: I naively gave it a try, and after having a quick glance through the results several genes were 'identified' that from a biological perspective made sense.

FWIW2: it turned out that a somewhat related question was recently posted and answered on the Bioconductor support pages: https://support.bioconductor.org/p/9140296/ (suitability of using `limma` for constrained data).

**Comment by GabrielHoffman** [comment]
`variancePartition` makes the same assumptions as `limma`.  So Gordon Smyth's remarks apply to `variancePartition` as well.  I think his suggestion of the `y2 <- asin(sqrt(y/100))` transform is a good way to go.

Cheers,
Gabriel
