### ISSUE TITLE
Can microarray type normalized and transformed data be used as input to dream like with limma?

### ISSUE THREAD

**Issue by hermidalc** [GabrielHoffman/variancePartition#44]
Can dream be used with microarray type normalized and log2 transformed input data (e.g. RMA, GC-RMA) like regular limma can?

Is it as simple as running the standard limma workflow except using the `dream` function instead of `lmFit`?

**Comment by GabrielHoffman** [comment]
Any normalized dataset that you would analyze with `limma::lmFit()` can be analyzed with `dream()` and other `variancePartition` functions.  If you use `dream()` with only fixed effects, then results will be exactly the same as from `limma`.
