### ISSUE TITLE
to evaluate the significance on random effect、

### ISSUE THREAD

**Issue by chengarthur** [GabrielHoffman/variancePartition#45]
Dear Dr. Hoffman:
I am working with a RNA expression data with a 10  levels category and serval other fixed effects as followed:
                  donor      diease   age 
sample1      1                 0          15
sample2      4                 1          53
sample3      2                 1          32
sample4      1                 0          12
So I  set the form like form <- ~ diease+age +(1|donor)
However as I have another supplymental data that could help me to evaluate the donor specific difference exsiting (I applied a test on the NULL model: donors have no difference with my supplymental data and get a p-value for it )and I want  compare the effectiveness of my supppmental data with your Dream method. However because I treat the donor as a random effect in dream model,  I could not find the p value in Dreamobject, and if i use the fixed model the Multicollinearity between donor and other factors would be too high and it would also be hard to pick a specific p value for campareplot. Are there any approach for Dream for VariancePartion to draw a significance conclusion for random effect factor like anova or directly to give a p value?

**Comment by GabrielHoffman** [comment]
The contribution of `Donor` can be evaluated using a variance partitioning analysis with `fitExtractVarPartModel()`.  That will give you the fraction of variance explained.  If you include other properties of a donor (i.e. sex, age, disease state), these variables with absorb some of the variation away from the donor component.

`dream()` only supports hypothesis testing on fixed effects.  The challenge is 1) computational expense, and 2) properly defining the null distribution.  With one 1 random effect, the null can be defined and the random effect can be tested using [RLRsim](https://cran.r-project.org/web/packages/RLRsim/).  But this is not built into dream.  With more than 1 random effect, I am not aware of a solution.  

If you want to get a sense of whether donor is important, without performing a formal hypothesis test, you can perform a bootstrap analysis.  Check out [`varPartConfInf`](https://gabrielhoffman.github.io/variancePartition/reference/varPartConfInf.html).  But it can be slow more moderated size datasets and number of boostraps.

Cheers,
Gabriel
