### ISSUE TITLE
R can't find makeContrastsDream 

### ISSUE THREAD

**Issue by bl24** [GabrielHoffman/variancePartition#47]
Hello,

I'm trying to do a dream analysis as outlined in the Bioconductor tutorial but I can't get the makeContrastsDream function to work. The help documentation appears when I run ?makeContrastsDream but when I actually try to make the matrix I get an error message saying that the function cannot be found. 

Regards,
Branden

**Comment by GabrielHoffman** [comment]
Hi, 
Install the latest version from GitHub, restart R, and try again

Gabriel

**Comment by bl24** [comment]
Great, thanks! That fixed it.
