### ISSUE TITLE
Hi, Is there a way to use the Dream package to test for Differential Transcript Usage

### ISSUE THREAD

**Issue by niradsp** [GabrielHoffman/variancePartition#49]
Is there any way that I can do this?
If not, would it be possible to extend this package to look for Isoform Usage?  Limma seems to already have a test for Isoform Usage called Diffsplice.  
I am running Dream at the Gene Expression level where I am using Subject and Batch as random effects.  Currently there are no mixed effects Isoform Usage package available.  So what I am doing is  treating Donor and Batch as fixed effects.  There are packages available for this,  such as DEXSeq, DRIMSeq,Diffsplice, etc.

Thanks,
Nirad

**Comment by GabrielHoffman** [comment]
Hi,
I figure you aware of this, but I want to make sure we are on the same page.

There are (at least) two related ideas here involving transcripts.  See https://liorpachter.wordpress.com/2018/02/15/gde²-dge²-dtu²-dte₁²-dte₂²/

1) Differential transcript expression: 
  Here, each transcript is considered separately and the expression of a given transcript is analysed just like each gene is.  You can easily use limma/dream for this.

2) Differential transcript *usage*:
 This considers *relative* transcript usage.  Intuitively, this could consider the *ratio* of transcripts A and B.
This is not currently implemented, but I am actively working on it.


Cheers,
Gabriel

**Comment by niradsp** [comment]
Hello Gabriel,

Yes, I am aware of the difference between Isoform Expression and Isoform Usage. Obviously, Isoform Expression is not so different from DGE, so this would be easy to do with Dream or Limma.
I want to look at relative expression.
May I ask when you think the Isoform Usage implementation will be ready?

Thanks,
Nirad

**Comment by GabrielHoffman** [comment]
Hi Nirad, 
Unfortunately, I have to finished a few projects first, so at least a few weeks.  You can get most of the way there by using the log ratio of a given transcript vs the sum of all other transcripts from that gene.  For one gene, construct a DTU matrix for each gene where each row is `log(A / rest)`.  Then cbind these across genes, and run dream.  This won't model the precision weights, but you will be able to use the linear mixed model

Gabriel

**Comment by niradsp** [comment]
Hello Gabriel,
Thank you for the response.  
So basically, if we have two isoforms:
take the expression of the first isoform and divide by the rest of the gene expression (add up all the remaining isoform expression).  Then take the log (do I do log2?).
Do the same for the second isoform. 

Is there a reason why the denominator is "rest" rather than "total"?

Should I create a matrix for each gene separately? In other words, if I have 10 genes, I will have 10 matrices, or do I create one big matrix? It is probably one big matrix, but just want to make sure.

This will give me a DTU matrix. Then run Dream on the matrix?
And I don't need the expression data, right?

Also, what is the implied distribution?  We are just assuming normal distribution?  

Will this be different from straight up running the lme4 package? 

How should I adjust the p-value?  The typical method is to take each gene, and adjust the p-value on the isoforms.  I assume I need to do this by myself.

I think though that I am not in a super hurry, so I can wait a few weeks no problem.

**Comment by GabrielHoffman** [comment]
I'm too busy to get into more detail right now.  But you have a good start.  I'll get back to you when the DTU extension to dream is ready
