### ISSUE TITLE
dream function extremely slow after parallelized part and before it completes and returns the prompt

### ISSUE THREAD

**Issue by hermidalc** [GabrielHoffman/variancePartition#5]
This section of of the `dream` function code is extremely slow with my dataset.  While the parallelized part before takes ~200s on 12 cores it prints to the console the `Total: 200 s` message and then you see that only one R thread is running and then it takes more than 10 more minutes to finish and return the prompt.  Do you know why?

https://github.com/GabrielHoffman/variancePartition/blob/1bc3a2f7eac85d0496812ac1a84e3b8e85fcfdb1/R/fitMixedModelDE.R#L583-L671

**Comment by GabrielHoffman** [comment]
What BiocParallel backend are you using: SnowParam(), MulticoreParam()? What OS?

**Comment by hermidalc** [comment]
> What BiocParallel backend are you using: SnowParam(), MulticoreParam()? What OS?

Linux and MulticoreParam().  It runs with all cores until it prints `Total: xxx s` right at line 583, then you see that it only goes to using a single core at 100% and it runs for a very long time before it finishes and returns the R prompt.

**Comment by GabrielHoffman** [comment]
Can you try with SnowParam and tell me if it makes a difference.  I’ll get back to this tomorrow

**Comment by hermidalc** [comment]
> Can you try with SnowParam and tell me if it makes a difference. I’ll get back to this tomorrow

Sorry for the delay, even with SnowParam it has the same problem where after it prints out the `Total: xxx s` time it runs for a very long time on the code shown above using only a single core.

**Comment by GabrielHoffman** [comment]
Do you see this if you run it in a fresh R session?

Can you give me a reproducible example?

**Comment by NathanSkene** [comment]
I've got the same problem. Will try to create a simple reproducible example.

**Comment by GabrielHoffman** [comment]
I have found that this is often a problem in interactive R sessions.  The parallel backend can crash and not restart.  

A few options
1) Reduce the number of cores, I've found this helps.
2) Do you have the same issue in a fresh R session?
3) Use local multithreading settings here: http://bioconductor.org/packages/devel/bioc/vignettes/variancePartition/inst/doc/FAQ.html#errors-with-biocparallel-multithreading-backend

Cheers,
Gabriel

**Comment by NathanSkene** [comment]
Hi Gabriel,

Many thanks for your prompt response. I've tried reducing cores and still get the issues you suggest. Also tried switching from to MulticoreParam. 

Have made a reproducible example. I find that it takes 168s to get it to print "Total: 168 s" then it's nine minutes for the function to then finish and return to the prompt.

[dummyVoomData2.rda.zip](https://github.com/GabrielHoffman/variancePartition/files/4941603/dummyVoomData2.rda.zip)

Code to reproduce is:
```
load(file="dummyVoomData2.rda")
form <- ~ logA + logB + logC + gender + RIN + group + total_reads_scaled + (1|indv.x) 
vobjDream = voomWithDreamWeights( meanDat, form, annot3 ,BPPARAM=MulticoreParam(workers=30))
fitmm = dream( vobjDream, form, annot3  ,BPPARAM=MulticoreParam(30))
```

Really appreciate your assistance with this (and the fact you developed this brilliant package in the first place!).

**Comment by GabrielHoffman** [comment]
Hi Nathan,
 Your code works fine for me using variancePartition v1.19.7 on R/4.0.1 on OS X and R/3.6.0 on Ubuntu both with Intel CPUs.  There are two steps to the parallel process, 1) run analysis in parallel and 2) collect the results from each thread.  Your machine seems to be struggling with step 2.  I have seen this before (see FAQ) and I've found that using `SnowParam()` reduces the chance of this issue.  

Can you show me your `sessionInfo()`?  Is the issue reproducible on other machine?

I like your work, so I'm curious what your application is

Gabriel
