### ISSUE TITLE
possible test failure with development version of lme4

### ISSUE THREAD

**Issue by bbolker** [GabrielHoffman/variancePartition#51]
Hi,

I'm in the process of sending a new version of `lme4` to CRAN. It looks like this might break `variancePartition` tests, although I'm having a little bit of trouble digging in and finding out exactly what the issue is (I have a development version of R, which gives me some challenges in installing Bioconductor packages).

Possibly? because a previously OK fit becomes singular? Related to https://github.com/lme4/lme4/issues/669 ?

update: something as simple as this breaks:

```r
library(variancePartition)
data(varPartData)
form <- ~ Age + (1|Individual) + (1|Tissue) + (1|Batch)
varPart <- fitExtractVarPartModel( geneExpr, form, info )
```

> Dividing work into 10 chunks...
boundary (singular) fit: see help('isSingular')
Error: BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error:
Error in run_model_check_mixed(fit, showWarnings, dream, colinearityCutoff, : boundary (singular) fit: see help('isSingular')

**Comment by GabrielHoffman** [comment]
Thanks fo the notice.
1) What version of variancePartition?
2) Can you point me to the new lme4 version, so I can reproduce the error

Gabriel

**Comment by bbolker** [comment]
I think this is resolved, see https://github.com/lme4/lme4/issues/676 ; still testing though.

**Comment by bbolker** [comment]
Actually, now I'm not sure. There *was* a bug that I fixed (`bootMer` doesn't inherit control settings of the original fit), but if we don't use `control` to suppress singularity checks then `calcVarPart` seems to be responsible for escalating messages to errors?

Running the example above with `verbose=TRUE` shows that in the same run (98) the message appears as both a message and an error: this must be happening due to `calcVarPart` ... ?  This happens [here](https://github.com/GabrielHoffman/variancePartition/blob/master/R/checkModelStatus.R#L124-L125=). **If** the original model was run with singularity-checking turned off then this doesn't happen, but if it was run "vanilla" (as in this case) then the behaviour that's happening seems to be as intended/coded in `calcVarPart` ... ?

On the other hand, I can easily imagine that in the less-minimal example you started with, the singularity-checking *was* being suppressed in the original model fit but then incorrectly ignored by `bootMer` ... ?  Can you re-try your less-minimal example with the most recent GitHub version of `lme4` ... ?


```r
set.seed(1)
bootRes2 = lme4::bootMer( fit, fixef, use.u=TRUE, nsim=100, parallel="no", ncpus=1, verbose=TRUE)
```

shows a singular-fit message on bootstrap replicate 98.

**Comment by GabrielHoffman** [comment]
Thanks for your patience.  It seems like the issue was with my internal checks rather than with `lme4::bootMer()`.  Version 1.25.13 posted now includes your original patch and a fix to this latest issue.
