### ISSUE TITLE
Error with plotStratify()

### ISSUE THREAD

**Issue by mikemwanga** [GabrielHoffman/variancePartition#55]
Hey there,

I tried to plot stratified expression based on cell type using the plotStratify() function. I ended up with the below error!
Kindly assist.

Code

`i = which.max(varPart$phenotype) #returns gene with highest variation based on cell_type

GE = data.frame(Expression = expr_matrix[i,], Cell_Type = metadata$phenotype) #returns gene values across the samples

#plot expression stratified by Cell type
plotStratify(Expression ~ Cell_Type, GE, main=rownames(expr_matrix)[i])`

Error

`

Error in `f()`:
! Insufficient values in manual scale. 2 needed but only 0 provided.
Backtrace:
  1. base `<fn>`(x)
  2. ggplot2:::print.ggplot(x)
  4. ggplot2:::ggplot_build.ggplot(x)
  5. base::lapply(data, scales_map_df, scales = npscales)
  6. ggplot2 FUN(X[[i]], ...)
     ...
 13. ggplot2 FUN(X[[i]], ...)
 14. self$map(df[[j]])
 15. ggplot2 f(..., self = self)
 16. self$palette(n)
 17. ggplot2 f(...)
 Error in f(...) :
20.
stop(fallback)
19.
signal_abort(cnd, .file)
18.
abort(glue("Insufficient values in manual scale. {n} needed but only {length(values)} provided."))
17.
f(...)
16.
self$palette(n)
15.
f(..., self = self)

`

**Comment by GabrielHoffman** [comment]
Thanks for the report. Can you provide a minimal reproducible example, and the results of `sessionInfo()`

Gabriel

**Comment by mikemwanga** [comment]
data = read.table("./data_expression2.txt",sep="\t", header=TRUE)
head(data)

         Gene Expression Cell_Type
1  GSM1350856    78.1767        T4
2  GSM1350857    88.9555        T4
3  GSM1350858    87.8738        T4
4  GSM1350859    94.0728        T4
5  GSM1350860    83.5585        T4
6  GSM1350861    72.0640        T4
7  GSM1355982  1934.2760 monocytes
8  GSM1355983  2881.7340 monocytes
9  GSM1355984  2596.6500 monocytes
10 GSM1355985  2821.9180 monocytes
11 GSM1355986  2813.5020 monocytes
12 GSM1355987  2851.1580 monocytes


plotStratify(Expression ~ Cell_Type, data)

**Comment by mikemwanga** [comment]
The above throws a similar error

**Comment by mikemwanga** [comment]
`data = read.table("./data_expression2.txt",sep="\t", header=TRUE)
head(data)

plotStratify(Expression ~ Cell_Type, data)`
[data_expression2.txt](https://github.com/GabrielHoffman/variancePartition/files/8903605/data_expression2.txt)

**Comment by GabrielHoffman** [comment]
I will fix this in the next release.  In the meantime, this works...
```r
data = read.table("./data_expression2.txt",sep="\t", header=TRUE)

data$Cell_Type = factor(data$Cell_Type)

plotStratify(Expression ~ Cell_Type, data)
```

Gabriel

**Comment by mikemwanga** [comment]
Thank you. This worked
