### ISSUE TITLE
Why are my adjusted p-values all the same in my output form my dream analysis?

### ISSUE THREAD

**Issue by dahrendorff** [GabrielHoffman/variancePartition#57]
Hi Dr. Hoffman,
 I apologize in advance if this has been answered elsewhere. I was wondering why most of my adjusted p-values in my analysis using dream are the same.

Thank you so much for your time,

Jan Dahrendorff

![same_Padjusted_vaules](https://user-images.githubusercontent.com/54722385/178343315-b72471ca-cb8f-4967-b249-3f6be35bc120.png)

**Comment by GabrielHoffman** [comment]
While p-values are uniformly distributed under the null, the FDR values (i.e. adjusted p-values) are not:

```r
set.seed(1)

pvalues = runif(1000)
fdr = p.adjust(pvalues, "fdr")

# smallest FDR
head(sort(fdr))
#> [1] 0.6442782 0.6442782 0.6442782 0.9524897 0.9524897 0.9524897

# largest FDR
tail(sort(fdr))
#> [1] 0.9981073 0.9981073 0.9981073 0.9981073 0.9999306 0.9999306
```

This is not related to this software, just the property of FDR

Gabriel

**Comment by dahrendorff** [comment]
Thank you, I appreciate your advice!
