### ISSUE TITLE
Remove batch effect before fitting the model

### ISSUE THREAD

**Issue by evaesquinas** [GabrielHoffman/variancePartition#59]
In the tutorial in appears 3? ways to remove the batch before fitting the model. However, I am not sure if there are 3 different ways or if at least two have to be done together.

1) First - Analysis on residuals:
```
library('limma')
# subtract out effect of Batch
fit <- lmFit( geneExpr, model.matrix(~ Batch, info))
res <- residuals( fit, geneExpr)
# fit model on residuals
form <- ~ (1|Tissue) + (1|Individual) + Age
varPartResid <- fitExtractVarPartModel( res, form, info )
```

2) Second - Remove batch effect with linear mixed model
```
# subtract out effect of Batch with linear mixed model
modelFit <- fitVarPartModel( geneExpr, ~ (1|Batch), info )
res <- residuals( modelFit )
# fit model on residuals
form <- ~ (1|Tissue) + (1|Individual) + Age
varPartResid <- fitExtractVarPartModel( res, form, info )
```

3) Third - residuals computed more efficiently:
```
# extract residuals directly without storing intermediate results
residList <- fitVarPartModel( geneExpr, ~ (1|Batch), info,
fxn=residuals )
# convert list to matrix
residMatrix = do.call(rbind, residList)
```

**Are first and second way really independent or should I run both steps/ways? If they are independent, what is the difference between them? I know that the third way is to avoid keeping large intermediate results, but I don't really understand the difference between using `limma` or not.**

On the other hand, I realised that the "first" way keeps the gene names in the rows but it is not the case for the "second" way, gene names are gone. Screenshots attached.

![1](https://user-images.githubusercontent.com/78473997/180834684-3b1319ee-19e7-4b12-b135-309d9851954f.JPG)
![2](https://user-images.githubusercontent.com/78473997/180835370-bad1e100-6ef0-4689-ad9f-236144fdb9c9.JPG)

**Is there a way to keep the gene names using the second way?**

In any case, I want to remove the batch effect of 3 variables (library prep, place, type of tube) in order to get the adjusted counts (and save this file) and run the linear mixed models to get the real effect in my biological data.

I was using `combat_seq` (`sva` package) to adjust by batch but I am currently having problems adding more variables to the batch effect. I have seen that people use `removeBatchEffect` from `limma` but, since I have to use the results in my linear mixed models, I don´t know if I will get good results. 

**Is there any good choice/recommendation that I could use to run linear mixed models with `variancePartition adjusting by 3 variables`?** 

Thanks very much in advance

Regards

**Comment by GabrielHoffman** [comment]
Thanks for your question. More recent versions make computing residuals easier, so see below.

Option 1 and 2 differ above because they account for `Batch` as a fixed vs random effect, so you only need to do one of them.  

When doing a differential expression analysis, I recommend fitting a single model with both the batch and other confounding variables in addition to the variable of interest.  Fitting this joint model accounts for the covariance between the variable of interest and confounders.  If you do a 2 step model of 1) fitting confounders and getting residuals, and 2) regression variable of interest on residuals, you will get an increased false positive rate.


R code:
```r
library(variancePartition)
data(varPartData)

# but older version should work for this too
packageVersion("variancePartition")
#> [1] '1.27.2'

form <- ~ (1|Batch) + (1|Individual) + (1|Tissue) + Height

fit = dream( geneExpr[1:10,], form, info)
#> Dividing work into 1 chunks...
#> 
#> Total:0.8 s
fit = eBayes(fit)

# view top genes
#topTable( fit )

# extract residuals from dream fit
res = residuals(fit)

res[1:3, 1:4]
#>               s1         s2          s3          s4
#> gene1  1.0234435 -0.9366438  0.77569526 -1.31700956
#> gene2 -0.7364306  0.2106597 -0.55920070  1.27414127
#> gene3  0.3434944 -1.1747666  0.01900945  0.09420459
```

**Comment by evaesquinas** [comment]
Thanks very much for you quick reply. 

What if you do not want to do differential expression analysis? What if you only want to assess the contribution of several biological variables (such as age, diabetes, sex, hypertension, cholesterol, etc) to the expression variation of each gene? Or in reality when you are running the linear mixed models you are doing differential expression analyses when you have categorical variables with more than 1 level?

How does it recognize the model when you need to remove batch effects from more than 1 variable? (imagine that there are 3 different variables that produce a lot of noise in the genetic expression and you want to remove that effect to see the real biological impact). Could I mix in the formula the 3 different variables and the biological information?
form <- ~ (1|Batch) + (1|Individual) + (1|Tissue) + Height

If a 2 step model can give you an increased false positive rate, what is the advantage of using it? 

Thanks very much in advance again

Regards

**Comment by GabrielHoffman** [comment]
Q1: Computing residuals are good for PCA, clustering after removing technical or confounding variables that are not of biological interest.  So removing batch is a good application

Q1.1: Yes, that works.

Q3: `fitExtractVarPartModel()` takes a matrix not a list.  So `fitExtractVarPartModel( residList, form, info )` should be `fitExtractVarPartModel( residMatrix, form, info )`

I recommend upgrading to a more recent version (https://diseaseneurogenomics.github.io/variancePartition), there have been substantial upgrades and bug fixes since 1.22.0

Gabriel

**Comment by evaesquinas** [comment]
Dear Gabriel Hoffman,

Thank you so much for your quick reply again.

About Q3, if I use `fitExtractVarPartModel( residMatrix, form, info )` after having  used `fitVarPartModel`, **wouldn't I get an increased false positive rate since I am doing in the process in two steps?** Because I am fitting the model twice...
```
library(variancePartition)
data(varPartData)

# extract residuals directly without storing intermediate results
residList <- fitVarPartModel( geneExpr, ~ (1|Batch), info,
                              fxn=residuals )
# convert list to matrix
residMatrix = do.call(rbind, residList)

form <- ~ (1|Tissue) + (1|Individual) + Age
result <- fitExtractVarPartModel( residMatrix, form, info )
```

Finally, **could I use `residMatrix` as my adjusted data for future analyses or it was not created for that purpose?** I have been trying to use `[combat_seq](https://github.com/zhangyuqing/ComBat-seq)` (sva package) but I am having a lot of problems to adjust my data and since I am interested in 1) adjust/correct my data and 2) get the contribution of several variables to the expression variation of each gene, I would like to know if this will be possible.

Thanks very much again

**Comment by GabrielHoffman** [comment]
Yes, I'm not advocating using that approach, just addressing the implementation question.  You should fit the covariates and variable of interest in a single model.

You can use `residMatrix` downstream for PCA, clustering, etc.  The motivation is pretty similar as for Combat

**Comment by evaesquinas** [comment]
Noted. Thanks very much for all your replies and time expend in answering.

Regards

**Comment by evaesquinas** [comment]
Noted, I understand.

My final question (sorry), is it possible to remove the batch effect and get the variance fractions in a single model and avoid doing a 2 step approach?

Thanks very much again for your help.

Regards

**Comment by GabrielHoffman** [comment]
Yes, you can fit one model and then remove the effect of Batch:

```r
library(variancePartition)
data(varPartData)

# fit full model
form <- ~ (1|Tissue) + (1|Individual) + (1|Batch) + Age
vp  <- fitExtractVarPartModel( geneExpr, form, info )
#> Dividing work into 10 chunks...
#> 
#> Total:13 s

# Compute variance fractions removing the effect of Batch
vp_corrected = t(apply(vp, 1, function(x){
  # compute variance fractions with out Batch
  y = x - x[['Batch']]
  y / sum(y)
  }))
incl = colnames(vp_corrected) != "Batch"
vp_corrected = data.frame(vp_corrected[,incl])

# New variance fraction with Batch remove
head(vp_corrected)
#>       Individual     Tissue           Age  Residuals
#> gene1  0.8909198 0.02454977 -1.127469e-04 0.08464320
#> gene2  0.8060388 0.10101116  3.336694e-04 0.09261633
#> gene3  0.8985738 0.03360169 -9.623934e-04 0.06878693
#> gene4  0.7688275 0.12531360  1.014416e-03 0.10484444
#> gene5  0.6997313 0.20909304  3.871499e-05 0.09113695
#> gene6  0.7284124 0.16749155  3.745512e-04 0.10372149
```

**Comment by evaesquinas** [comment]
Thanks very much, I really appreciate your quick reply.

How would you get the corrected counts? (the full dataframe with all samples in order to use it for future analyses)

Could the function `vp_corrected` be used more than once (if you have 3 batches or more) or will it have another approach to compute the fractions?

Thanks in advance again and sorry for any inconvenience

**Comment by GabrielHoffman** [comment]
I understand better now.  The varianceParttition software deals with log2 CPM rather than modeling the counts directly. So it reproduced residuals that are log2 CPM corrected for covariates.    Unfortunately, there is no way to directly "correct" the observed counts

**Comment by evaesquinas** [comment]
I did not know that the results from `fitExtractVarPartModel` were log2 CPM corrected for covariates... I did not see anything in the vignette...

Checking the vignette again, it appears that the gene matrix that you use as your input has to be normalized and this count can be normalized using counts per million (CPM), reads per kilobase per million (RPKM) or fragments per kilobase per million (FPKM). 

**I am using log2(TPM counts + 1) as my input, is it a problem for the function?** Because maybe I am getting incorrect results and I do not know.

Look forward to your reply,

Thanks very much in advance

**Comment by evaesquinas** [comment]
Thanks very much for your answer, I did not know that `fitExtractVarPartModel` was generating residuals log2 CPM corrected for covariates.

Thanks for your time answering during the whole issue.
Regards
