### ISSUE TITLE
Sparse matrix input

### ISSUE THREAD

**Issue by cnk113** [GabrielHoffman/variancePartition#6]
Hello,

I'm trying to use a single cell dataset, but I'm getting a matrix too large error. I was wondering if you had plans to make the tool accept sparse matrix input for fitExtractVarPartModel?

Thanks,
Chang

**Comment by GabrielHoffman** [comment]
I've used variancePartition on imputed single cell data, but that is not sparse.  I haven't tried with a sparseMatrix, but it shouldn't be to hard to make it work

Can you you give a minimal reproducible example?

**Comment by cnk113** [comment]
Sorry did you want a reproducible example of the error? The dataset has 104k cells and 36k genes. However I've uploaded 2500 single cell dataset here which is in a sparse matrix format.
[mtx.rds.zip](https://github.com/GabrielHoffman/variancePartition/files/4068319/mtx.rds.zip)

**Comment by GabrielHoffman** [comment]
Yes.  Can you give a code example and some fake data that give this error?  I need to be able to reproduce the error before I can fix it

**Comment by cnk113** [comment]
Ah well the error is not really with the any particular code in variancePartition.
`Error in asMethod(object) :                       
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105`
Comes from just turning my sparse matrix format into a matrix.

**Comment by GabrielHoffman** [comment]
In that case, you should be able to run variancePartition in batches were each batch is a subset of genes that is small enough to fit in memory.

**Comment by GabrielHoffman** [comment]
I've though about this some more, and I should be able to modify the existing code to process a sparse matrix in a way that is hidden from the user. 

I won't have time to make the change until next week, but I will let you know when it is finished.  

Thanks for the suggestion

- Gabriel

**Comment by GabrielHoffman** [comment]
I have solved this issue in v1.17.3

CHANGES IN VERSION 1.17.3
-------------------------
	o Allow sparseMatrix for gene expression.  Now saves memory by avoiding conversion to matrix.  Processing sparseMatrix will be slower, but memory usage will be low. 

Can you try it?

- Gabriel
