### ISSUE TITLE
There are NA values -- Missing data is not allowed 

### ISSUE THREAD

**Issue by DMPKendo** [GabrielHoffman/variancePartition#68]
Hello, 

I am getting the errors for the missing values. 

varPart <- fitExtractVarPartModel( geneExpr, form, info )
Error for .fitExtractVarPartModel(as.matrix(exprObj), formula, data, REML = REML: 
  There are 12 NA/NaN/Inf values in exprObj
Missing data is not allowed

Do we need to remove the samples with missing values?

Thank you!

**Comment by GabrielHoffman** [comment]
Yes, missing data is the response (i.e. `geneExpr`) is not allowed.  You mush remove genes with missing data
