### ISSUE TITLE
p-values of the correlation from "canCorPairs"

### ISSUE THREAD

**Issue by se2cheeese** [GabrielHoffman/variancePartition#69]
Hi, thank you very much for your great tool. 
I wonder if it would be possible to get the p-values for the correlation from canCorPairs.

**Comment by GabrielHoffman** [comment]
Its not currently implemented in `variancePartition`, but you can adapt the `canCorPairs()` code https://github.com/DiseaseNeuroGenomics/variancePartition/blob/HEAD/R/canCorPairs.R and include a test from the CCP package https://cran.r-project.org/web/packages/CCP/

**Comment by se2cheeese** [comment]
Thanks for the quick response. I will try as you recommend.
