### ISSUE TITLE
just the toy dataset example not working.

### ISSUE THREAD

**Issue by zntaylgit** [GabrielHoffman/variancePartition#71]
> data(varPartData)
> form <- ~ Age + (1|Individual) + (1|Tissue) + (1|Batch) 
> varPart <- fitExtractVarPartModel( geneExpr, form, info )
Dividing work into 100 chunks...
boundary (singular) fit: see help('isSingular')

Total:2 s
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
In addition: Warning messages:
1: In serialize(data, node$con, xdr = FALSE) :
  'package:stats' may not be available when loading
2: In serialize(data, node$con, xdr = FALSE) :
  'package:stats' may not be available when loading
> vp <- sortCols( varPart )
Error in sortCols(varPart) : object 'varPart' not found
> plotPercentBars( vp[1:10,] )
Error in plotPercentBars(vp[1:10, ]) : object 'vp' not found
> plotVarPart( vp )
Error in plotVarPart(vp) : object 'vp' not found

**Comment by GabrielHoffman** [comment]
Can you show sessionInfo().  Does restarting R fix this?

**Comment by zntaylgit** [comment]
No, but updating R did fix it.
