### ISSUE TITLE
Error in if (inherits(possibleError, "error") && grep("the fixed-effects model matrix is column rank deficient",  :    missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by stanleyjs** [GabrielHoffman/variancePartition#72]
Hi

I am trying to run VariancePartition on a pseudo-bulked single cell dataset.

The model runs fine on single cell data. However, when I aggregate the data into pseudobulks, I get this error:
```

Error in if (inherits(possibleError, "error") && grep("the fixed-effects model matrix is column rank deficient",  : 
  missing value where TRUE/FALSE needed
```

My info matrix looks like this:

```
       pt_number condition batch
1:CTR         1       CTR     1
2:CTR         3       CTR     2
3:CTR         5       CTR     3
4:CTR         7       CTR     4
5:CTR         9       CTR     5
6:CTR        11       CTR     6
1:HIV         2       HIV     1
2:HIV         4       HIV     2
3:HIV         6       HIV     3
4:HIV         8       HIV     4
5:HIV        10       HIV     5
6:HIV        12       HIV     6
```

My design matrix is
form <- ~ (1|condition) + (1|batch) + (1|pt_number) 

The problem persists even if I do

form <- ~ (1|pt_number) 

It seems to be related to pt_number, as the following design works
form <- ~ (1|condition) + (1|batch)

**Comment by GabrielHoffman** [comment]
The issue is that `pt_number` has only 1 observation per level, so there is not variation *within* level.  What version of `variancePartition` are you using?  A more recent version should give a clearer error

**Comment by stanleyjs** [comment]
Isn't there variance between the pt_numbers, though? I thought variance
partition was reporting the variance along a certain experimental variable.

**Comment by stanleyjs** [comment]
For example, if gene j has 0.2 in column "condition" (a categorical
variable with two values), then 20% of the variance in gene j is found
across the condition states. Am I interpreting this correctly?

Jay

**Comment by GabrielHoffman** [comment]
I see the issue now.  The problem is that by using `(1|pt_number)`, you are modeling it as a categorical variable with a random effect.  Since each category only has one observation (i.e.  `pt_number` 3 is only observed once) the model is not full rank.  Can you show the result of `sessionInfo()`
