### ISSUE TITLE
Adjusting R2

### ISSUE THREAD

**Issue by MEladawi** [GabrielHoffman/variancePartition#86]
Hello--

Thanks for the great package. 

I just had a question, why the calculation of the variance partition using R2 does does include adjusting the R2 values?

Thanks!
Mahmoud

**Comment by GabrielHoffman** [comment]
See links for thoughts on adjusted R^2 when returning to this in the future
- https://en.wikipedia.org/wiki/Coefficient_of_determination#Adjusted_R2
- https://doi.org/10.1177/1094428106292901
