### ISSUE TITLE
voomWithDreamAndQualityWeights?

### ISSUE THREAD

**Issue by knokknok** [GabrielHoffman/variancePartition#87]
Would be nice to also include quality-weights (from voomWithQualityWeights) with dream.

**Comment by GabrielHoffman** [comment]
You can included pre-estimated quality weights with the upcoming version of variancePartition.  However, estimating quality weights with a linear mixed model is statistically challenging, it is not just an implementation issue.  Other users have asked about this, and it seems doable.  But other feature requests have been more pressing.

Best,
Gabriel
