### ISSUE TITLE
p-values

### ISSUE THREAD

**Issue by palbioinfor** [GabrielHoffman/variancePartition#90]
Thank you for the package , it works great 👍

 

I have a few questions that I might have failed to understand-

 

1. After using _'fitExtractVarPartModel'_ function I wonder about the significance of the genes showing the variance for different variablles used in the model because I am not sure if all the associations are supposed to be significant. How can I get the p-values/ adj- p-values here.

 

2. I used following set to fit the model for each gene separately  and  was able to get the t-value and adj p-values for all genes .

_form_test <- count[gene,] ~var1+(1|var2)         #var1-fixed effect

  fit <- lmer(form_test, info, REML = FALSE)

  summary_result <- summary(fit)_

 

But I do not find much concordance in this result (using lmer for each gene as above) with what is reported after using _'fitExtractVarPartModel'_ (as point1).

I understand that 'fitExtractVarPartModel' fits the regression model for each gene and returns the variance fractions by using calcVarPart but I am little confused to see the genes showing up in variance fraction which are not showing up in lmer result at all.

 

For example result of gene1 after 'fitExtractVarPartModel' show % variance with var1 and var2

 

For the same gene lmer is -

Variable | Estimate | Std..Error | df | t.value | Pr...t..
-- | -- | -- | -- | -- | --
(Intercept) | -0.01665 | 0.1569 | 10.71841 | -0.1924677 | 0.85926592
Var1 | 0.046037 | 0.05423 | 10.93063 | 1.361447 | 0.23742828

<br class="Apple-interchange-newline">

Here the t-val/Pr(>|t|) does not seem to be significant for the fixed effect but it is reported by 'fitExtractVarPartModel' with %variance contributed from var1. Kindly help me understand if I am missing something to understand here.

Thanks in advance

**Comment by GabrielHoffman** [comment]
Thanks for the question.

1) Variance partitioning analysis *estimates* the fraction of variance explained by each variable.  You can't get p-values directly from this analysis.  If you really want confidence intervals on the fractions, you can use [`varPartConfInf()`](https://diseaseneurogenomics.github.io/variancePartition/reference/varPartConfInf.html).  For *hypothesis testing* you need to use `dream()` to test a fixed effect variable.

2) For samples sizes < ~100, the sampling variation of the variance fractions can be substantial.  This causes some genes with high estimated variance fraction for some variable not showing a significant association with that variable.  You can use [`varPartConfInf()`](https://diseaseneurogenomics.github.io/variancePartition/reference/varPartConfInf.html) to get some intuition about this

With RNA-seq count data, the `variancePartition` workflow uses voom-style precision weights, so `lmer()` is called with weights.  This is likely why you don't exactly reproduce the `variancePartition` results

Best,
Gabriel

**Comment by palbioinfor** [comment]
Thank you so much for the explanation. Really helpful.

🙏

**Comment by dev3105** [comment]
hey @GabrielHoffman, 
I was using simulated data in variancePartition package. While running the command: "varPart <-fitExtractVarPartModel(geneExpr, form, info)".   There was error: "Error in .fitExtractVarPartModel(exprObj, formula, data, REML = REML,  : 
  Initial model failed:
function 'chm_factor_ldetL2' not provided by package 'Matrix'. "


I tried installing Matrix package but the error persist.


Please help!!!
