### ISSUE TITLE
Large difference in results between v1.28.9 and v1.35.3

### ISSUE THREAD

**Issue by alexvpickering** [GabrielHoffman/variancePartition#99]
Hello and thank you for the great package. I am just trying to figure out the cause of a large difference in the results of a model fit that I originally ran with `variancePartition` 1.28.9 and the results that I am getting now with version 1.35.3. For the particular contrast, the number of significant genes went from ~650 to ~100. I was able to reproduce the original analysis and results by using the old version, so I am confident that it is related to an update in the package. Do you have any sense as to any major changes that may have caused this and if so, whether the prior results are invalid? Here is an outline of the script that led to this:

```R
library(Biobase)
library(limma)
library(BiocParallel)
library(variancePartition)
library(edgeR)

eset <- qs::qread('eset.qs')

# setup pdata
pdata <- pData(eset)

# filter genes by number of counts
counts <- exprs(eset)
isexpr <- rowSums(cpm(counts)>0.1) >= 5
counts <- counts[isexpr, ]

form <- ~
  0 +
  group +
  age_years +
  disease_duration_years +
  (1|sample_id) +
  (1|disease_subcategory)

# get library size normalization factors
lib.size <- eset$lib.size * eset$norm.factors

# estimate weights using linear mixed model of dream
vobjDream <- voomWithDreamWeights(counts, form, pdata, lib.size = lib.size, BPPARAM=param)

L <- makeContrastsDream(
  form,
  pdata,
  contrasts = c(
    baseline_NR_vs_TR = "groupbaseline_lte_30 - groupbaseline_gte_70",
    week18_NR_vs_TR = 'groupweek_18_lte_30 - groupweek_18_gte_70',
    week18_NR_vs_baseline_NR = 'groupweek_18_lte_30 - groupbaseline_lte_30',
    week18_TR_vs_baseline_TR = 'groupweek_18_gte_70 - groupbaseline_gte_70'
))

fitmm <- dream(vobjDream, form, pdata, L)
fitmm <- variancePartition::eBayes(fitmm)

tt <- variancePartition::topTable(fitmm, coef='baseline_NR_vs_TR', number=Inf)

# this has changed from ~650 to ~100
sum(tt$adj.P.Val < 0.05)
```

Thank you!

**Comment by GabrielHoffman** [comment]
Looking at the [logs](https://diseaseneurogenomics.github.io/variancePartition/news/index.html), v1.28.9 is from March 14, 2023.  Looking at the updates since then, I completely reimpleted the backend to
- fix some bugs
- improve convergence checks,
- identify genes where the model fails,
- substantially reduce false positives with small sample size

So I trust the updated version more, especially with `n <= 20`

**Comment by alexvpickering** [comment]
Thanks @GabrielHoffman. This particular dataset is fairly large (`n= 127`) so I wouldn't expect that to be particularly relevant here. Were these major bugs? So much so that you would not trust the results of the previous version?

**Comment by GabrielHoffman** [comment]
I am not aware of any major issues.  But in general, I haven't found that interpreting differences in the number of differentially expressed genes to be too informative.   If it changed from 650 to 0, or 0 to 5000, then I'd be concerned.  But your change is small enough.  For a more rigorous test, you can plot the t-statistics from the two versions against each other

**Comment by alexvpickering** [comment]
Thanks for the suggestion. It looks like the t-statistics are quite similar, while the pvalues and FDRs are apparently quite a bit different (plots are for the ~650 originally significant genes comparing previous fit to updated fit; dashed line is x=y):

![image](https://github.com/GabrielHoffman/variancePartition/assets/15719520/34df14ec-738e-46e6-af3c-855b2d0a3d83)

![image](https://github.com/GabrielHoffman/variancePartition/assets/15719520/1878969b-a9c4-4b00-aac8-c098048dafcc)

![image](https://github.com/GabrielHoffman/variancePartition/assets/15719520/cdaf7b74-df22-4cf1-a88d-f978a9968716)


What do you make of the above if anything?

**Comment by GabrielHoffman** [comment]
There look very concordant.  The p-values and the FDR from the new fit are a bit more conservative, consistent with what I expected.  While the t-statistics, p-values and FDR are very concordant, the number of significant genes is a summary statistic of the data that is pretty sensitive to small changes so its not great for interpretation on its own.

**Comment by alexvpickering** [comment]
Cheers - thanks so much for helping me work this and for the incredibly useful package!
